sonar.projectKey=sofia-tasklist-frontend-final
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.{ts,tsx}
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,src/main.tsx,src/vite-env.d.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts,src/__tests__/**,src/types/**
sonar.cpd.exclusions=src/__tests__/**
sonar.junit.reportPaths=reports/junit.xml